### ISSUE TITLE
Wrong name of implementation

### ISSUE THREAD

**Issue by tranquoctrungcntt** [rishabh876/RoundedImageView#1]
implementation 'com.rishabhharit.roundedimageview:roundedImageView:0.7.0' => fail to resolve

=>implementation 'com.rishabhharit.roundedimageview:RoundedImageView:0.7.0' => success

**Comment by rishabh876** [comment]
Hi @tranquoctrungcntt, thank you for reporting the issue. I have fixed the name and have updated the version as well.
